USE Pokemon;


DROP TABLE Entrenador;

CREATE TABLE Entrenador(
    ID INT(5) PRIMARY KEY,
    Nombre VARCHAR(20) UNIQUE NOT NULL,
    Contraseña VARCHAR(255) NOT NULL,
    Ganadas INT DEFAULT 0,
    Perdidas INT DEFAULT 0,
    Imagen LONGBLOB 
);

SELECT * FROM Entrenador;

DROP TABLE Especie;

CREATE TABLE Especie(
	NumPokedex INT PRIMARY KEY,
	Nombre VARCHAR(50) UNIQUE NOT NULL,
	PSBase INT NOT NULL,
	ATKBase INT NOT NULL,
	DEFBase INT NOT NULL,
	VELBase INT NOT NULL,
	SDEFBase INT NOT NULL,
	SATKBase INT NOT NULL,
	Tipo1 VARCHAR(50) NOT NULL,
	Tipo2 VARCHAR(50),
    NomRegion VARCHAR(20) NOT NULL,
	FOREIGN KEY(NomRegion) REFERENCES Region (Nombre),
	Imagen LONGBLOB
);

SELECT * FROM Especie;

DROP TABLE Region;

CREATE TABLE Region(
	Nombre VARCHAR(20) PRIMARY KEY,
    Generacion VARCHAR(25) NOT NULL,
    NumPokemon INT DEFAULT 0
);

SELECT * FROM Region;

DROP TABLE Pokemon;

CREATE TABLE Pokemon(
	ID INT(5) PRIMARY KEY,
    IDEntrenador INT(5) NOT NULL,
    FOREIGN KEY(IDEntrenador) REFERENCES Entrenador(ID),
    Favorito BOOLEAN DEFAULT FALSE,
    Mote VARCHAR(20),
    Genero VARCHAR(20) NOT NULL,
    HabEspecial VARCHAR(50) NOT NULL,
    NumPokedex INT NOT NULL,
    FOREIGN KEY(NumPokedex) REFERENCES Especie(NumPokedex),
    PS INT NOT NULL,
    ATK INT NOT NULL,
    DEF INT NOT NULL,
    VEL INT NOT NULL,
    SDEF INT NOT NULL,
    SATK INT NOT NULL,
    Objeto VARCHAR(30),
    Naturaleza VARCHAR(50) NOT NULL,
    IVPS INT NOT NULL,
    IVATK INT NOT NULL,
    IVDEF INT NOT NULL,
    IVVEL INT NOT NULL,
    IVSDEF INT NOT NULL,
    IVSATK INT NOT NULL,
    EVPS INT NOT NULL,
    EVATK INT NOT NULL,
    EVDEF INT NOT NULL,
    EVVEL INT NOT NULL,
    EVSDEF INT NOT NULL,
    EVSATK INT NOT NULL
);

SELECT * FROM Pokemon;    

DROP TABLE Posee;

CREATE TABLE Posee(
	NomMoviemiento VARCHAR(30) PRIMARY KEY,
	IDPokemon INT(5) NOT NULL,
    MasPP BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(IDPokemon) REFERENCES Pokemon(ID)
);

SELECT * FROM Posee;   

DROP TABLE Movimiento;

CREATE TABLE Movimiento(
	Nombre VARCHAR(30) NOT NULL,
    PP INT DEFAULT 0,
    FOREIGN KEY(Nombre) REFERENCES Posee(NomMoviemiento)
);


