package com.mycompany.pokemonbd;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author hiram
 */
public class DatosUsuario extends javax.swing.JPanel implements ActionListener{
    private String idEntrenador;
    BD mBD = new BD();
    ImagenAlmacenEntrenador mImagen = new ImagenAlmacenEntrenador();
    /**
     * Creates new form datosUsuario
     */
    public DatosUsuario(String idEntrenador) {
        this.idEntrenador = idEntrenador;
        initComponents();
        cargarImagen();
        cargarDatos();
        pokemon_favorito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        saludo_label = new javax.swing.JLabel();
        nombre_label = new javax.swing.JLabel();
        idEntrenador_label = new javax.swing.JLabel();
        pk_favorito = new javax.swing.JLabel();
        favorito_label = new javax.swing.JLabel();
        ganadas_label = new javax.swing.JLabel();
        perdidas_label = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        perfil = new javax.swing.JLabel();
        pk_favorito_nombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 26, 33));
        setForeground(new java.awt.Color(22, 26, 33));
        setMinimumSize(new java.awt.Dimension(1150, 690));

        jPanel2.setBackground(new java.awt.Color(22, 26, 33));
        jPanel2.setForeground(new java.awt.Color(22, 26, 33));

        saludo_label.setBackground(new java.awt.Color(255, 255, 255));
        saludo_label.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        saludo_label.setForeground(new java.awt.Color(255, 255, 255));
        saludo_label.setText("Hola, + Nombre Usuario");

        nombre_label.setBackground(new java.awt.Color(255, 255, 255));
        nombre_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre_label.setForeground(new java.awt.Color(255, 255, 255));
        nombre_label.setText("Nombre: ");

        idEntrenador_label.setBackground(new java.awt.Color(255, 255, 255));
        idEntrenador_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idEntrenador_label.setForeground(new java.awt.Color(255, 255, 255));
        idEntrenador_label.setText("IDPokemon Entrenador:");

        pk_favorito.setBackground(new java.awt.Color(255, 255, 255));
        pk_favorito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pk_favorito.setForeground(new java.awt.Color(255, 255, 255));
        pk_favorito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pk_favorito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        favorito_label.setBackground(new java.awt.Color(255, 255, 255));
        favorito_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        favorito_label.setForeground(new java.awt.Color(255, 255, 255));
        favorito_label.setText("Pokemon favorito:");

        ganadas_label.setBackground(new java.awt.Color(255, 255, 255));
        ganadas_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ganadas_label.setForeground(new java.awt.Color(255, 255, 255));
        ganadas_label.setText("Batallas ganadas:");

        perdidas_label.setBackground(new java.awt.Color(255, 255, 255));
        perdidas_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        perdidas_label.setForeground(new java.awt.Color(255, 255, 255));
        perdidas_label.setText("Batallas perdidas:");

        imagen.setBackground(new java.awt.Color(13, 17, 23));
        imagen.setForeground(new java.awt.Color(13, 17, 23));
        imagen.setLayout(null);
        imagen.add(perfil);
        perfil.setBounds(0, 0, 260, 260);

        pk_favorito_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pk_favorito_nombre.setForeground(new java.awt.Color(255, 255, 255));
        pk_favorito_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_label)
                            .addComponent(idEntrenador_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ganadas_label)
                            .addComponent(perdidas_label))
                        .addGap(226, 226, 226))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saludo_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(favorito_label)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pk_favorito, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(pk_favorito_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(saludo_label)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_label)
                            .addComponent(ganadas_label))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perdidas_label)
                            .addComponent(idEntrenador_label)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(favorito_label)
                .addGap(15, 15, 15)
                .addComponent(pk_favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pk_favorito_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel favorito_label;
    private javax.swing.JLabel ganadas_label;
    private javax.swing.JLabel idEntrenador_label;
    private javax.swing.JPanel imagen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JLabel perdidas_label;
    private javax.swing.JLabel perfil;
    private javax.swing.JLabel pk_favorito;
    private javax.swing.JLabel pk_favorito_nombre;
    private javax.swing.JLabel saludo_label;
    // End of variables declaration//GEN-END:variables
    public void cargarImagen(){
        ArrayList imagenUser = mBD.cargarImagen(idEntrenador);
        if (mBD.conectar()) {
            byte[] datos = (byte[]) imagenUser.get(0);
            Image foto = new ImageIcon(datos).getImage();
            ImageIcon icono = new ImageIcon(foto.getScaledInstance(265,265,Image.SCALE_SMOOTH));
            perfil.setIcon(icono);
        }
    }

    public void pokemon_favorito(){
        ArrayList datos = mBD.obtener_pokemon_favorito(idEntrenador);
        String nombre = datos.get(0).toString();
        String mote = datos.get(1).toString();
        String NombreF;
        if (mote.equals("")) {
            NombreF = nombre;
        } else {
            NombreF = mote;
        }
        pk_favorito_nombre.setText(NombreF);
        byte[] datosImagen = (byte[]) datos.get(3);
        Image foto = new ImageIcon(datosImagen).getImage();
        ImageIcon icono = new ImageIcon(foto.getScaledInstance(151,151,Image.SCALE_SMOOTH));
        pk_favorito.setIcon(icono);
    }

    public void cargarDatos(){
        ArrayList datos = mBD.obtenerDatos(idEntrenador);
        if (mBD.conectar()) {
            saludo_label.setText("Hola " + datos.get(0));
            nombre_label.setText("Nombre: " + datos.get(0));
            idEntrenador_label.setText("ID Entrenador: " + idEntrenador);
            ganadas_label.setText("Batallas ganadas: " + datos.get(1));
            perdidas_label.setText("Batallas perdidas: " + datos.get(2));
        }
    }

    @Override
    public void actionPerformed(ActionEvent evt) {
    }
}
