/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonbd;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author hiram
 */
public class ListaPK extends javax.swing.JFrame implements ActionListener {
    private static String idEntrenador;
    /**
     * Creates new form ListaPK
     */
    public ListaPK() {
        initComponents();
        setIconImage(new ImageIcon("Icono.jpg").getImage());
        this.setTitle("Lista de Pokemones");
    }

    public ListaPK(String idEntrenador) {
        this.idEntrenador = idEntrenador;
        initComponents();
        setIconImage(new ImageIcon("Icono.png").getImage());
        this.setTitle("Lista de Pokemones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ventana = new javax.swing.JPanel();
        informacion = new javax.swing.JPanel();
        opciones = new javax.swing.JTabbedPane();
        datos = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        perfil = new javax.swing.JLabel();
        nombre_label = new javax.swing.JLabel();
        mote_label = new javax.swing.JLabel();
        objeto_label = new javax.swing.JLabel();
        naturaleza_label = new javax.swing.JLabel();
        genero_label = new javax.swing.JLabel();
        num_label = new javax.swing.JLabel();
        region_label = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        estadisticas = new javax.swing.JPanel();
        tituloes = new javax.swing.JLabel();
        imagen1 = new javax.swing.JPanel();
        perfil1 = new javax.swing.JLabel();
        nombre_label1 = new javax.swing.JLabel();
        ps_label = new javax.swing.JLabel();
        ataque_label = new javax.swing.JLabel();
        defensa_label = new javax.swing.JLabel();
        atq_especial_label = new javax.swing.JLabel();
        def_especial_label = new javax.swing.JLabel();
        velocidad_label = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        totalBase_t = new javax.swing.JTextField();
        velocidadBase_t = new javax.swing.JTextField();
        defespecialBase_t = new javax.swing.JTextField();
        atqespecialBase_t = new javax.swing.JTextField();
        defensaBase_t = new javax.swing.JTextField();
        ataqueBase_t = new javax.swing.JTextField();
        psBase_t = new javax.swing.JTextField();
        base_label = new javax.swing.JLabel();
        ivs_label = new javax.swing.JLabel();
        ps_ivs_t = new javax.swing.JTextField();
        atq_ivs_t = new javax.swing.JTextField();
        def_ivs_t = new javax.swing.JTextField();
        atq_especial_ivs_t = new javax.swing.JTextField();
        def_especial_ivs = new javax.swing.JTextField();
        vel_ivs_t = new javax.swing.JTextField();
        total_ivs_t = new javax.swing.JTextField();
        total_evs_t = new javax.swing.JTextField();
        vel_evs_t = new javax.swing.JTextField();
        def_especial_evs_t = new javax.swing.JTextField();
        atq_especial_evs_t = new javax.swing.JTextField();
        def_evs_t = new javax.swing.JTextField();
        atq_evs_t = new javax.swing.JTextField();
        ps_evs_t = new javax.swing.JTextField();
        evs_label = new javax.swing.JLabel();
        estadistica_label = new javax.swing.JLabel();
        ps_total_t = new javax.swing.JTextField();
        atq_total_t = new javax.swing.JTextField();
        def_total_t = new javax.swing.JTextField();
        atq_especial_total_t = new javax.swing.JTextField();
        def_especial_total_t = new javax.swing.JTextField();
        vel_total_t = new javax.swing.JTextField();
        movimientos = new javax.swing.JPanel();
        titutlo_mov = new javax.swing.JLabel();
        contenedor_movimientos = new javax.swing.JScrollPane();
        movimietos_tabla = new javax.swing.JTable();
        panel_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        user = new javax.swing.JButton();
        favorito = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        personas = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 820));
        setPreferredSize(new java.awt.Dimension(1350, 820));
        getContentPane().setLayout(null);

        ventana.setBackground(new java.awt.Color(13, 17, 23));
        ventana.setForeground(new java.awt.Color(255, 255, 255));
        ventana.setMinimumSize(new java.awt.Dimension(1350, 820));
        ventana.setPreferredSize(new java.awt.Dimension(1350, 764));

        informacion.setBackground(new java.awt.Color(22, 26, 33));
        informacion.setForeground(new java.awt.Color(22, 26, 33));

        opciones.setBackground(new java.awt.Color(22, 26, 33));
        opciones.setForeground(new java.awt.Color(255, 255, 255));
        opciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        datos.setBackground(new java.awt.Color(22, 26, 33));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Datos del pokemon");

        imagen.setBackground(new java.awt.Color(13, 17, 23));
        imagen.setForeground(new java.awt.Color(13, 17, 23));
        imagen.setLayout(null);
        imagen.add(perfil);
        perfil.setBounds(0, 0, 210, 210);

        nombre_label.setBackground(new java.awt.Color(255, 255, 255));
        nombre_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre_label.setForeground(new java.awt.Color(255, 255, 255));
        nombre_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_label.setText("Nombre:");

        mote_label.setBackground(new java.awt.Color(255, 255, 255));
        mote_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mote_label.setForeground(new java.awt.Color(255, 255, 255));
        mote_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mote_label.setText("Mote:");

        objeto_label.setBackground(new java.awt.Color(255, 255, 255));
        objeto_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        objeto_label.setForeground(new java.awt.Color(255, 255, 255));
        objeto_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        objeto_label.setText("Objeto:");

        naturaleza_label.setBackground(new java.awt.Color(255, 255, 255));
        naturaleza_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        naturaleza_label.setForeground(new java.awt.Color(255, 255, 255));
        naturaleza_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naturaleza_label.setText("Naturaleza:");

        genero_label.setBackground(new java.awt.Color(255, 255, 255));
        genero_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genero_label.setForeground(new java.awt.Color(255, 255, 255));
        genero_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genero_label.setText("Género:");

        num_label.setBackground(new java.awt.Color(255, 255, 255));
        num_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_label.setForeground(new java.awt.Color(255, 255, 255));
        num_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num_label.setText("Número Pokedex:");

        region_label.setBackground(new java.awt.Color(255, 255, 255));
        region_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        region_label.setForeground(new java.awt.Color(255, 255, 255));
        region_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        region_label.setText("Región:");

        eliminar.setBackground(new java.awt.Color(184, 44, 0));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Liberar Pokemon");
        eliminar.addActionListener(this);

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datosLayout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(titulo))
                        .addGroup(datosLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre_label)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mote_label)
                                .addComponent(objeto_label)
                                .addComponent(naturaleza_label)
                                .addComponent(genero_label)
                                .addComponent(num_label)
                                .addComponent(region_label)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo)
                .addGap(38, 38, 38)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre_label)
                .addGap(18, 18, 18)
                .addComponent(mote_label)
                .addGap(18, 18, 18)
                .addComponent(objeto_label)
                .addGap(18, 18, 18)
                .addComponent(naturaleza_label)
                .addGap(18, 18, 18)
                .addComponent(genero_label)
                .addGap(80, 80, 80)
                .addComponent(num_label)
                .addGap(18, 18, 18)
                .addComponent(region_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(eliminar))
        );

        opciones.addTab("Datos", datos);

        estadisticas.setBackground(new java.awt.Color(22, 26, 33));

        tituloes.setBackground(new java.awt.Color(255, 255, 255));
        tituloes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloes.setForeground(new java.awt.Color(255, 255, 255));
        tituloes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloes.setText("Estadisticas del pokemon");

        imagen1.setBackground(new java.awt.Color(13, 17, 23));
        imagen1.setForeground(new java.awt.Color(13, 17, 23));
        imagen1.setLayout(null);
        imagen1.add(perfil1);
        perfil1.setBounds(0, 0, 210, 210);

        nombre_label1.setBackground(new java.awt.Color(255, 255, 255));
        nombre_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre_label1.setForeground(new java.awt.Color(255, 255, 255));
        nombre_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_label1.setText("Nombre:");

        ps_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ps_label.setForeground(new java.awt.Color(255, 255, 255));
        ps_label.setText("PS");

        ataque_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ataque_label.setForeground(new java.awt.Color(255, 255, 255));
        ataque_label.setText("Ataque");

        defensa_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defensa_label.setForeground(new java.awt.Color(255, 255, 255));
        defensa_label.setText("Defensa");

        atq_especial_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atq_especial_label.setForeground(new java.awt.Color(255, 255, 255));
        atq_especial_label.setText("Atq. Especial");

        def_especial_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        def_especial_label.setForeground(new java.awt.Color(255, 255, 255));
        def_especial_label.setText("Def. Especial");

        velocidad_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        velocidad_label.setForeground(new java.awt.Color(255, 255, 255));
        velocidad_label.setText("Velocidad");

        total_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_label.setForeground(new java.awt.Color(255, 255, 255));
        total_label.setText("Total");

        totalBase_t.setEditable(false);
        totalBase_t.setBackground(new java.awt.Color(13, 17, 23));
        totalBase_t.setForeground(new java.awt.Color(255, 255, 255));
        totalBase_t.setText("0");

        velocidadBase_t.setEditable(false);
        velocidadBase_t.setBackground(new java.awt.Color(13, 17, 23));
        velocidadBase_t.setForeground(new java.awt.Color(255, 255, 255));
        velocidadBase_t.setText("0");

        defespecialBase_t.setEditable(false);
        defespecialBase_t.setBackground(new java.awt.Color(13, 17, 23));
        defespecialBase_t.setForeground(new java.awt.Color(255, 255, 255));
        defespecialBase_t.setText("0");

        atqespecialBase_t.setEditable(false);
        atqespecialBase_t.setBackground(new java.awt.Color(13, 17, 23));
        atqespecialBase_t.setForeground(new java.awt.Color(255, 255, 255));
        atqespecialBase_t.setText("0");

        defensaBase_t.setEditable(false);
        defensaBase_t.setBackground(new java.awt.Color(13, 17, 23));
        defensaBase_t.setForeground(new java.awt.Color(255, 255, 255));
        defensaBase_t.setText("0");

        ataqueBase_t.setEditable(false);
        ataqueBase_t.setBackground(new java.awt.Color(13, 17, 23));
        ataqueBase_t.setForeground(new java.awt.Color(255, 255, 255));
        ataqueBase_t.setText("0");

        psBase_t.setEditable(false);
        psBase_t.setBackground(new java.awt.Color(13, 17, 23));
        psBase_t.setForeground(new java.awt.Color(255, 255, 255));
        psBase_t.setText("0");

        base_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        base_label.setForeground(new java.awt.Color(255, 255, 255));
        base_label.setText("Base");

        ivs_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ivs_label.setForeground(new java.awt.Color(255, 255, 255));
        ivs_label.setText("IVs");

        ps_ivs_t.setEditable(false);
        ps_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        ps_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        ps_ivs_t.setText("0");

        atq_ivs_t.setEditable(false);
        atq_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_ivs_t.setText("0");

        def_ivs_t.setEditable(false);
        def_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        def_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        def_ivs_t.setText("0");

        atq_especial_ivs_t.setEditable(false);
        atq_especial_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_especial_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_especial_ivs_t.setText("0");

        def_especial_ivs.setEditable(false);
        def_especial_ivs.setBackground(new java.awt.Color(13, 17, 23));
        def_especial_ivs.setForeground(new java.awt.Color(255, 255, 255));
        def_especial_ivs.setText("0");

        vel_ivs_t.setEditable(false);
        vel_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        vel_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        vel_ivs_t.setText("0");

        total_ivs_t.setEditable(false);
        total_ivs_t.setBackground(new java.awt.Color(13, 17, 23));
        total_ivs_t.setForeground(new java.awt.Color(255, 255, 255));
        total_ivs_t.setText("0");

        total_evs_t.setEditable(false);
        total_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        total_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        total_evs_t.setText("0");

        vel_evs_t.setEditable(false);
        vel_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        vel_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        vel_evs_t.setText("0");

        def_especial_evs_t.setEditable(false);
        def_especial_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        def_especial_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        def_especial_evs_t.setText("0");

        atq_especial_evs_t.setEditable(false);
        atq_especial_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_especial_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_especial_evs_t.setText("0");

        def_evs_t.setEditable(false);
        def_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        def_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        def_evs_t.setText("0");

        atq_evs_t.setEditable(false);
        atq_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_evs_t.setText("0");

        ps_evs_t.setEditable(false);
        ps_evs_t.setBackground(new java.awt.Color(13, 17, 23));
        ps_evs_t.setForeground(new java.awt.Color(255, 255, 255));
        ps_evs_t.setText("0");

        evs_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evs_label.setForeground(new java.awt.Color(255, 255, 255));
        evs_label.setText("EVs");

        estadistica_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadistica_label.setForeground(new java.awt.Color(255, 255, 255));
        estadistica_label.setText("Estadística");

        ps_total_t.setEditable(false);
        ps_total_t.setBackground(new java.awt.Color(13, 17, 23));
        ps_total_t.setForeground(new java.awt.Color(255, 255, 255));
        ps_total_t.setText("0");

        atq_total_t.setEditable(false);
        atq_total_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_total_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_total_t.setText("0");

        def_total_t.setEditable(false);
        def_total_t.setBackground(new java.awt.Color(13, 17, 23));
        def_total_t.setForeground(new java.awt.Color(255, 255, 255));
        def_total_t.setText("0");

        atq_especial_total_t.setEditable(false);
        atq_especial_total_t.setBackground(new java.awt.Color(13, 17, 23));
        atq_especial_total_t.setForeground(new java.awt.Color(255, 255, 255));
        atq_especial_total_t.setText("0");

        def_especial_total_t.setEditable(false);
        def_especial_total_t.setBackground(new java.awt.Color(13, 17, 23));
        def_especial_total_t.setForeground(new java.awt.Color(255, 255, 255));
        def_especial_total_t.setText("0");

        vel_total_t.setEditable(false);
        vel_total_t.setBackground(new java.awt.Color(13, 17, 23));
        vel_total_t.setForeground(new java.awt.Color(255, 255, 255));
        vel_total_t.setText("0");

        javax.swing.GroupLayout estadisticasLayout = new javax.swing.GroupLayout(estadisticas);
        estadisticas.setLayout(estadisticasLayout);
        estadisticasLayout.setHorizontalGroup(
            estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasLayout.createSequentialGroup()
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estadisticasLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(tituloes))
                    .addGroup(estadisticasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_label1)
                            .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(base_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(ivs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(evs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(estadistica_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(ps_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(psBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ps_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ps_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ps_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(ataque_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(ataqueBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(atq_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(atq_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(atq_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(defensa_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(defensaBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(def_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(def_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(def_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(atq_especial_label, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(atqespecialBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(atq_especial_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(atq_especial_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(atq_especial_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(def_especial_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(defespecialBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(def_especial_ivs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(def_especial_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(def_especial_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(velocidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(velocidadBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(vel_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(vel_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(vel_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(estadisticasLayout.createSequentialGroup()
                                .addComponent(total_label)
                                .addGap(80, 80, 80)
                                .addComponent(totalBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(total_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(total_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        estadisticasLayout.setVerticalGroup(
            estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloes)
                .addGap(38, 38, 38)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(base_label)
                    .addComponent(ivs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evs_label)
                    .addComponent(estadistica_label))
                .addGap(10, 10, 10)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ps_label)
                    .addComponent(psBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ps_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ps_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ps_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ataque_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ataqueBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defensa_label)
                    .addComponent(defensaBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atq_especial_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atqespecialBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_especial_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_especial_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atq_especial_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def_especial_label)
                    .addComponent(defespecialBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_especial_ivs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_especial_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_especial_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(velocidad_label)
                    .addComponent(velocidadBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vel_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vel_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vel_total_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_label)
                    .addComponent(totalBase_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_ivs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_evs_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        opciones.addTab("Estadisticas", estadisticas);

        movimientos.setBackground(new java.awt.Color(22, 26, 33));

        titutlo_mov.setBackground(new java.awt.Color(255, 255, 255));
        titutlo_mov.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titutlo_mov.setForeground(new java.awt.Color(255, 255, 255));
        titutlo_mov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titutlo_mov.setText("Movimientos del pokemon");

        movimietos_tabla.setBackground(new java.awt.Color(13, 17, 23));
        movimietos_tabla.setForeground(new java.awt.Color(13, 17, 23));
        movimietos_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "PP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        movimietos_tabla.setRowHeight(70);
        movimietos_tabla.setSelectionBackground(new java.awt.Color(13, 17, 23));
        movimietos_tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        movimietos_tabla.getTableHeader().setReorderingAllowed(false);
        contenedor_movimientos.setViewportView(movimietos_tabla);

        javax.swing.GroupLayout movimientosLayout = new javax.swing.GroupLayout(movimientos);
        movimientos.setLayout(movimientosLayout);
        movimientosLayout.setHorizontalGroup(
            movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimientosLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(titutlo_mov)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movimientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedor_movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        movimientosLayout.setVerticalGroup(
            movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimientosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titutlo_mov)
                .addGap(114, 114, 114)
                .addComponent(contenedor_movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        opciones.addTab("Movimientos", movimientos);

        javax.swing.GroupLayout informacionLayout = new javax.swing.GroupLayout(informacion);
        informacion.setLayout(informacionLayout);
        informacionLayout.setHorizontalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        informacionLayout.setVerticalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_tabla.setBackground(new java.awt.Color(13, 17, 23));
        panel_tabla.setForeground(new java.awt.Color(255, 255, 255));

        tabla.setBackground(new java.awt.Color(13, 17, 23));
        tabla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Imagen", "Nombre / Especie", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(22, 26, 33));
        tabla.setRowHeight(120);
        tabla.setSelectionBackground(new java.awt.Color(13, 17, 23));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        user.setBackground(new java.awt.Color(13, 17, 23));
        user.setForeground(new java.awt.Color(13, 17, 23));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Usuario.png"))); // NOI18N
        user.setBorder(null);
        user.addActionListener(this);
        user.setToolTipText("Ir al perfil del usuario");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        favorito.setBackground(new java.awt.Color(13, 17, 23));
        favorito.setForeground(new java.awt.Color(13, 17, 23));
        favorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Favorito.png"))); // NOI18N
        favorito.setBorder(null);
        favorito.setToolTipText("Asignar pokemon como favorito");
        favorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritoActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(13, 17, 23));
        agregar.setForeground(new java.awt.Color(13, 17, 23));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agregar.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setToolTipText("Agregar un nuevo pokemon a la lista");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addActionListener(this);

        personas.setBackground(new java.awt.Color(13, 17, 23));
        personas.setForeground(new java.awt.Color(13, 17, 23));
        personas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Personas.png"))); // NOI18N
        personas.setBorder(null);
        personas.setToolTipText("Ver a los demas usuarios");
        personas.addActionListener(this);
        personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaLayout = new javax.swing.GroupLayout(ventana);
        ventana.setLayout(ventanaLayout);
        ventanaLayout.setHorizontalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaLayout.createSequentialGroup()
                        .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(ventanaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(favorito)
                        .addGap(18, 18, 18)
                        .addComponent(agregar)
                        .addGap(18, 18, 18)
                        .addComponent(personas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user)
                        .addGap(312, 312, 312))))
        );
        ventanaLayout.setVerticalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ventanaLayout.createSequentialGroup()
                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(ventana);
        ventana.setBounds(-10, 0, 1590, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void favoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favoritoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarActionPerformed

    private void personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField ataqueBase_t;
    private javax.swing.JLabel ataque_label;
    private javax.swing.JTextField atq_especial_evs_t;
    private javax.swing.JTextField atq_especial_ivs_t;
    private javax.swing.JLabel atq_especial_label;
    private javax.swing.JTextField atq_especial_total_t;
    private javax.swing.JTextField atq_evs_t;
    private javax.swing.JTextField atq_ivs_t;
    private javax.swing.JTextField atq_total_t;
    private javax.swing.JTextField atqespecialBase_t;
    private javax.swing.JLabel base_label;
    private javax.swing.JScrollPane contenedor_movimientos;
    private javax.swing.JPanel datos;
    private javax.swing.JTextField def_especial_evs_t;
    private javax.swing.JTextField def_especial_ivs;
    private javax.swing.JLabel def_especial_label;
    private javax.swing.JTextField def_especial_total_t;
    private javax.swing.JTextField def_evs_t;
    private javax.swing.JTextField def_ivs_t;
    private javax.swing.JTextField def_total_t;
    private javax.swing.JTextField defensaBase_t;
    private javax.swing.JLabel defensa_label;
    private javax.swing.JTextField defespecialBase_t;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel estadistica_label;
    private javax.swing.JPanel estadisticas;
    private javax.swing.JLabel evs_label;
    private javax.swing.JButton favorito;
    private javax.swing.JLabel genero_label;
    private javax.swing.JPanel imagen;
    private javax.swing.JPanel imagen1;
    private javax.swing.JPanel informacion;
    private javax.swing.JLabel ivs_label;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mote_label;
    private javax.swing.JPanel movimientos;
    private javax.swing.JTable movimietos_tabla;
    private javax.swing.JLabel naturaleza_label;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JLabel nombre_label1;
    private javax.swing.JLabel num_label;
    private javax.swing.JLabel objeto_label;
    private javax.swing.JTabbedPane opciones;
    private javax.swing.JPanel panel_tabla;
    private javax.swing.JLabel perfil;
    private javax.swing.JLabel perfil1;
    private javax.swing.JButton personas;
    private javax.swing.JTextField psBase_t;
    private javax.swing.JTextField ps_evs_t;
    private javax.swing.JTextField ps_ivs_t;
    private javax.swing.JLabel ps_label;
    private javax.swing.JTextField ps_total_t;
    private javax.swing.JLabel region_label;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloes;
    private javax.swing.JLabel titutlo_mov;
    private javax.swing.JTextField totalBase_t;
    private javax.swing.JTextField total_evs_t;
    private javax.swing.JTextField total_ivs_t;
    private javax.swing.JLabel total_label;
    private javax.swing.JButton user;
    private javax.swing.JTextField vel_evs_t;
    private javax.swing.JTextField vel_ivs_t;
    private javax.swing.JTextField vel_total_t;
    private javax.swing.JTextField velocidadBase_t;
    private javax.swing.JLabel velocidad_label;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables



    @Override
    public void actionPerformed(ActionEvent evt) {
        if(evt.getSource() == user){
            Usuario usuario = new Usuario(idEntrenador);
            usuario.setVisible(true);
            this.dispose();
        }
        if(evt.getSource() == personas){
            Global global = new Global(idEntrenador);
            global.setVisible(true);
            this.dispose();
        }

        if(evt.getSource() == agregar){
            AgregarNuevo agregar = new AgregarNuevo(this,true, idEntrenador);
            agregar.setVisible(true);
        }
    }

}
